Update failure_with_run_workflow.yml

diff --git a/.github/workflows/failure_with_run_workflow.yml b/.github/workflows/failure_with_run_workflow.yml
--- a/.github/workflows/failure_with_run_workflow.yml
+++ b/.github/workflows/failure_with_run_workflow.yml
@@ -1,27 +1,27 @@
-name : job fails also run workflow
+name: job fails also run workflow
 
-on: 
- workflow_dispatch
+on:
+  workflow_dispatch:
 
 jobs:
-    job1:
-        runs_on: ubunut_latest
-        steps: 
-          - name: failure job
-            run : exit 1
-    job2:
-        needs: job1
-        if: $ {{ always () }}
-        runs_on: ubuntu_latest
-        steps:
-          - name: continue job2
-            run: echo " this run even job1 fails"
+  job1:
+    runs-on: ubuntu-latest
+    steps:
+      - name: failure job
+        run: exit 1
 
-      job3:
-        needs: job2
-        if: $ {{ always () }}
-        runs_on: ubuntu_latest
-        steps:
-          - name: continue job3
-            run: echo " this run even job2 fails"
-            
+  job2:
+    needs: job1
+    if: $ {{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: continue job2
+        run: echo "this runs even if job1 fails"
+
+  job3:
+    needs: job2
+    if: $ {{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: continue job3
+        run: echo "this runs even if job2 fails"
